# Package Overview
package_name: amazonreview

# Data Files
train_path: train
validation_path: validation
test_path: test


model_name: amazonreview_model
model_save_file: amazonreview_model_output_v

# Feature engineering parameters


# Set the random seed


# Alogrithm parameters


# Mappings for calss labels
