
# Package Overview
package_name: amazon_sentiment_model

# Data Files
training_data_file: Reviews.csv
test_data_file: test.csv

# Variables
target: Sentiment

pipeline_name: sentiment_model
pipeline_save_file: sentiment_model_output_v

features:      # final features to be use
  - Text


unused_fields:  # Features to drop before pipeline
  - Id
  - ProductId
  - UserId
  - ProfileName
  - HelpfulnessNumerator
  - HelpfulnessDenominator
  - Score
  - Time
  - Summary

# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 100
max_depth: 10

optimizer: adam
loss: binary_crossentropy
accuracy_metric: accuracy